### ISSUE TITLE
HLS直播example一直黑屏

### ISSUE THREAD

**Issue by luckymoon** [LarchLiu/vue3-video-player#10]
![image](https://user-images.githubusercontent.com/17333401/132317310-e7f4a96a-73f2-4bfb-bcad-00158f5e8eda.png)
demo: https://cloudgeektech.com/vue3-video-player/
视频播放不了,控制台信息如图,  能解决下吗?

**Comment by luckymoon** [comment]
我使用自己的直播源也是这样的问题

**Comment by luckymoon** [comment]
![image](https://user-images.githubusercontent.com/17333401/132318030-78a83534-b5d6-4bf6-a35c-500a060c1168.png)

**Comment by LarchLiu** [comment]
应该就是直播源的问题，现在 demo 可以了。自己测试的时候注意直播源跟你自己的网址协议 http/https 一致。
先试试，有问题可以继续反馈。
