### ISSUE TITLE
Add customized control buttons to the video player

### ISSUE THREAD

**Issue by arpitharajanna** [LarchLiu/vue3-video-player#13]
How do we add additional control buttons like download button or delete button to the control bar in the video player

**Comment by LarchLiu** [comment]
You can add it in [controls.vue](https://github.com/LarchLiu/vue3-video-player/blob/c6657424b5a7ab19489b43ef1f7ef1f160d4d253/src/dashboard/controls.vue) such as fullscreen-control and build it by yourself.
