### ISSUE TITLE
TypeError: Cannot read properties of null

### ISSUE THREAD

**Issue by cnhuye** [LarchLiu/vue3-video-player#16]
Error: Uncaught (in promise) TypeError: Cannot read properties of null (reading 'slots')

in vue3-video-player.vue  line #134: 
...
    const ins = getCurrentInstance()
    this.slots = ins.slots ? ins.slots : {}
..

ins is null.

I'm using vue3 setup script.

**Comment by LarchLiu** [comment]
Could you give some sample code or test it in [demo](https://stackblitz.com/edit/vitejs-vite-rf6dum?file=src%2FApp.vue)?
