### ISSUE TITLE
Subtitle integration

### ISSUE THREAD

**Issue by Snoobie** [LarchLiu/vue3-video-player#18]
Hello,

First of all congratulations for the work that has been done.
Do you think it is possible to integrate subtitles in the video player easily?
What would be the best way to do it?

Thank you and wish you merry christmas :)

**Comment by LarchLiu** [comment]
You can refer to the integration of the [barrage layer](https://github.com/LarchLiu/vue3-video-player/blob/7368ec6627ee974aa7d89fa6f062cbe0d3b4994a/src/layers/barrage-layer.vue).
For the parsing of subtitle files can be found in [artplayer subtitle](https://github.com/zhw2590582/ArtPlayer/blob/5d8b4fb7cea68dcd92f3d4d30c10560ae3c2ac5e/packages/artplayer/src/subtitle.js).
PR welcome

**Comment by Snoobie** [comment]
Thank you for your reactivity ! 
Unfortunately for me, due to a lack of time and short deadline I had to opt for another solution.

**Comment by LarchLiu** [comment]
You can use [artplayer](https://github.com/zhw2590582/ArtPlayer) and there is a [demo](https://codesandbox.io/s/artplayer-vue-demo-forked-2p5tc?file=/src/App.vue) for subtitle.

Hope it helps.
