### ISSUE TITLE
组件实例销毁后视频流的线程依然存在，请问这个问题怎么解决？

### ISSUE THREAD

**Issue by 17797776321** [LarchLiu/vue3-video-player#19]
![image](https://user-images.githubusercontent.com/20875342/147575344-9906746c-6b70-42c1-a815-37e0710dad79.png)
![image](https://user-images.githubusercontent.com/20875342/147575384-29b2b124-c900-47b6-9a52-387d4c1e49a0.png)

**Comment by LarchLiu** [comment]
用最新版本的 @cloudgeek/playcore-hls@v0.1.3, 参考 [demo](https://stackblitz.com/edit/vitejs-vite-rf6dum?file=src%2FApp.vue), DOM 销毁前执行 destroyHls

enjoy & feedback
