### ISSUE TITLE
使用HLS时unmounted时未销毁组件

### ISSUE THREAD

**Issue by SkyMonkya** [LarchLiu/vue3-video-player#23]
hls加载视频切换页面后视频还继续缓冲，最新的版本（1.3.1-beta6）不能绑定viewCore无法销毁播放器。

**Comment by LarchLiu** [comment]
你说的 1.3.1-beta6 是什么版本？
用最新的[@cloudgeek/playcore-hls@0.1.4](https://github.com/LarchLiu/playcore-hls)，组件卸载时会主动销毁 hls。
如何手动销毁可以参考 #19。

enjoy & feedback

**Comment by SkyMonkya** [comment]
好的好的，之前hls安装的是0.1.4，多谢已经好了
