### ISSUE TITLE
全屏控制组件不在最下方？

### ISSUE THREAD

**Issue by shuguanglin** [LarchLiu/vue3-video-player#28]
_delete image _

**Comment by LarchLiu** [comment]
UI 设计问题，为什么一定要在最下面。上传的图片可能涉及版权问题，已编辑。

**Comment by shuguanglin** [comment]
> UI 设计问题，为什么一定要在最下面。上传的图片可能涉及版权问题，已编辑。
涉及到一个遮挡的问题，也有习惯的问题，感觉还是在最底部符合直觉，中间的话会有割裂感，以上。
