### ISSUE TITLE
Nuxt 3 or Typescript Support ?

### ISSUE THREAD

**Issue by sikeat7** [LarchLiu/vue3-video-player#29]
Hi! Does it support with typescript or support with nuxt 3 ?

**Comment by LarchLiu** [comment]
It's not support now, you can use [ArtPlayer](https://github.com/zhw2590582/ArtPlayer) that support SSR and good luck.

**Comment by sikeat7** [comment]
> It's not support now, you can use [ArtPlayer](https://github.com/zhw2590582/ArtPlayer) that support SSR and good luck.

Thank you! I have implementation ArtPlayer with Nuxt3 SSR but it not working. Or if you have a snippet code can you share to me. Appreciated
