### ISSUE TITLE
iOS safari 和Chrome视频源无法播放

### ISSUE THREAD

**Issue by yk81708090** [LarchLiu/vue3-video-player#3]
问题现象：
1.苹果手机访问（Safari）报未设置视频源

2.Mac系统 谷歌浏览器报视频无法正常播放

3.视频高度修改无效，依旧会自动全屏放大超屏幕，（备注：竖屏视频源）

请问有什么解决方法么？

**Comment by LarchLiu** [comment]
有试过 [Demo](https://cloudgeektech.com/vue3-video-player/) 吗？我测试在 Mac Big Sur 11.2.3 和 IOS 14 的 Safari 和 Chrome 都可以正常播放。至于高度是样式问题。用例可参考 [App.vue](https://github.com/LarchLiu/vue3-video-player/blob/8698ec02956d4f4507911ca6c5f8d5c48acb5115/src/App.vue) 或者 [Card.vue](https://github.com/LarchLiu/gh-twitter/blob/32cd31ad8ff2c693dec07016e903b22847120fcf/vue-twitter/src/components/Twitter/card.vue#L31)

**Comment by qq1059020841** [comment]
Safari 版本14.1 (16611.1.21.161.6) 实测无法使用  

渲染后的标签
<div class="video" data-v-29ba628a=""><vue3-video-player src="http://abc.com/video.mp4" data-v-29ba628a="" style="width: 100%; height: 100%;"></vue3-video-player></div>

**Comment by LarchLiu** [comment]
该控件用在了 [tvv](https://tvv.vercel.app/) 项目，大家可以帮忙测试是否能正常运行。let me know

**Comment by yk81708090** [comment]
试过demo，demo现象与我上面描述的现象一直，我使用的系统是 Mac 10.15.7  Safari版本14.1 Chrome版本 90.0.4430.93（正式版本） (x86_64)

大概一周后，我会接手该项目，届时我再反馈给你。

感谢您的回复！
