### ISSUE TITLE
vue3.2.31 使用会报错

### ISSUE THREAD

**Issue by hiddendeer** [LarchLiu/vue3-video-player#30]
TypeError: Cannot read properties of null (reading 'slots')
<img width="1129" alt="image" src="https://user-images.githubusercontent.com/35824281/167651100-45a30352-b0f2-4663-8f33-76ed7531abb0.png">

**Comment by LarchLiu** [comment]
[demo](https://stackblitz.com/edit/vitejs-vite-rf6dum?file=package.json) is ok with vue@3.2.31
