### ISSUE TITLE
为什么按示例运行总会出现这个错误

### ISSUE THREAD

**Issue by luckymoon** [LarchLiu/vue3-video-player#9]
![image](https://user-images.githubusercontent.com/17333401/131827069-935e2c7a-a30e-4d58-a5f4-41b826198456.png)

**Comment by LarchLiu** [comment]
vue 是什么版本？贴下你的 code 片段

**Comment by luckymoon** [comment]
``<template>
<div class="player-container">
    <div class="test-player-wrap">
      <vue3-video-player @play="playFunc" :src="src" :title="title" :view-core="viewCore"
      :cover="cover" :barrageConfig="{barrageList: barrages}" :logo="logo" resolution="720p">
      </vue3-video-player>
    </div>
</div>
</template>

<script>
const cover = 'https://img1.wxzxzj.com/maxresdefault.jpg'
export default {
    // components:{
    // },
    name: "videotest",
    data() {
        return {
            title: "视频测试",
            cover: cover,
            logo: require('@/assets/img/img.jpg'),
            src: "https://en-zo.dev/vue3-player-video.mp4",
            barrages: [],
            viewCore: [(_, config) => { console.log(config) }]
        }
    },
  methods: {
    playFunc () {
      console.log('play!!!!')
    },
  }
};
</script>

<style>
 .test-player-wrap {
  width: 720px;
  position: relative;
  margin: 30px auto;
}
</style>

**Comment by luckymoon** [comment]
> vue 是什么版本？贴下你的 code 片段

vue@3.1.0

**Comment by LarchLiu** [comment]
我测试了下 vue 3.2 之前的版本要尽量保证 vue 安装版本与 @vue/compiler-sfc 安装版本一致(可以查看package-lock.json 或 yarn.lock)，或者使用 vue 3.2.x 的版本，不用关注 @vue/compiler-sfc。原因不明，最好还是用 vue 的最新版本吧。

**Comment by luckymoon** [comment]
> @vue/compiler-sfc

嗯, 更新了vue 3.2.6版本就没有错误了
